package apalabrados.model;

// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class RegisterTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		//Relative path
		String path = System.getProperty("user.dir");
		System.setProperty("webdriver.chrome.driver", path + "/selenium/chromedriver.exe");
		System.out.println("setUp");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void register() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver","/apalabrados-tsw/selenium/chromedriver.exe");
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1576, 836));
		driver.findElement(By.id("refRegistrarse")).click();
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("inputUsername")).click();
		driver.findElement(By.id("inputUsername")).sendKeys("ana");
		driver.findElement(By.id("inputEmailRegister")).click();
		driver.findElement(By.id("inputEmailRegister")).sendKeys("ana@mail.com");
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("ana");
		driver.findElement(By.id("inputPassword2")).click();
		driver.findElement(By.id("inputPassword2")).sendKeys("ana");
		driver.findElement(By.id("btnRegistrarse")).click();
		Thread.sleep(1000);
		assertThat(driver.findElement(By.id("message")).getText(),
				is("Registrado correctamente. ¡Inicia sesión y juega!"));
		{
			String value = driver.findElement(By.id("inputEmail")).getAttribute("value");
			assertThat(value, is("ana@mail.com"));
		}
		{
			String value = driver.findElement(By.id("inputPwd")).getAttribute("value"); 
			assertThat(value, is("ana"));
		}
	}
}
