package apalabrados.model;

// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;


public class RegisterTest {
	private WebDriver driverP1, driverP2;
	
	@Before
	public void setUp() {
		//Relative path
		String path = System.getProperty("user.dir");
		System.setProperty("webdriver.chrome.driver", path + "/selenium/chromedriver.exe");
		
		driverP1 = new ChromeDriver();
		driverP1.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		driverP2 =  new ChromeDriver();
		driverP1.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}
	
	private void register(WebDriver driver, String userName, String mail, String pwd) throws InterruptedException {
		driver.get("http://localhost:8080/");
		//driver.manage().window().setSize(new Dimension(1576, 836));
		
		driver.findElement(By.id("refRegistrarse")).click();
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("inputUsername"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("inputUsername")).click();
		driver.findElement(By.id("inputUsername")).sendKeys(userName);
		driver.findElement(By.id("inputEmailRegister")).click();
		driver.findElement(By.id("inputEmailRegister")).sendKeys(mail);
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys(userName);
		driver.findElement(By.id("inputPassword2")).click();
		driver.findElement(By.id("inputPassword2")).sendKeys(userName);
		driver.findElement(By.id("btnRegistrarse")).click();
		Thread.sleep(1000);
		assertThat(driver.findElement(By.id("message")).getText(),
				is("Registrado correctamente. ¡Inicia sesión y juega!"));
		{
			String value = driver.findElement(By.id("inputEmail")).getAttribute("value");
			assertThat(value, is(mail));
		}
		{
			String value = driver.findElement(By.id("inputPwd")).getAttribute("value"); 
			assertThat(value, is(userName));
		}
	}


	@Test
	public void registerPepe() throws InterruptedException {
		//Sign-Up player 1 (pepe)
		register(driverP1, "pepe", "pepe@mail.com", "pepe");
	}
	
	@Test
	public void registerAna() throws InterruptedException {
		//Sign-Up player 2 (ana)
		register(driverP2, "ana", "ana@mail.com", "ana");
	}
	
	
	@After
	public void tearDown() {
		driverP1.quit();
		driverP2.quit();
	}

}
